projects:
  deltaGraphQL:
    schemaPath: src/store/graphql/schema.json
    includes:
      - src/store/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/store/graphql
extensions:
  amplify:
    version: 3
